### ISSUE TITLE
代码开源吗

### ISSUE THREAD

**Issue by vintingb** [hifn123p/YNU_WX#1]
老哥，代码开源吗

**Comment by hifn123p** [comment]
你要干嘛用

**Comment by vintingb** [comment]
> 你要干嘛用
> […](#)
> 在 2019年11月25日，15:33，vintingb ***@***.***> 写道： ﻿ 老哥，代码开源吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

最近自学python，学习一下，只想看爬虫

**Comment by vintingb** [comment]
你好，我尝试登录，由于它传输密码加密的
![TIM截图20191128222406](https://user-images.githubusercontent.com/54710337/69813780-dd121700-122d-11ea-948c-d1df4284038f.png)
但是我看见你的ppt上面传输是不加密的，请问你如何解决的

**Comment by hifn123p** [comment]
服务器代码丢失了，所以Python的代码找不到了，系统不一样吧，研究生这个系统表单那里就是明文。

你做的是本科生的吧。你仔细研究下网页源码那个请求是怎么发送的

**Comment by hifn123p** [comment]
![image](https://user-images.githubusercontent.com/13654278/69816097-a8548e80-1232-11ea-84fd-1c57e82e3158.png)

是AES加密的

**Comment by hifn123p** [comment]
源码找到了重新上传了
我看了一下，好像用的CryptoJS AES加密的

**Comment by vintingb** [comment]
@hifn123p 不对，是用rsa加密的，公匙放在js里面，是ABCDEFGHJKMNPQRSTWXYZabcdefhijkmnprstwxyz2345678

**Comment by vintingb** [comment]
@hifn123p 那可以模拟加密提交吗

**Comment by hifn123p** [comment]
可以
如果不要求效率，简单点可以用Selenium，模拟浏览器登录，就不用管怎么加密了

**Comment by vintingb** [comment]
@hifn123p 那就没意思了，我就是想学习一下，能不能帮一下，大佬

**Comment by hifn123p** [comment]
js我也不怎么会啊，最近没时间，过段时间可以研究下

**Comment by vintingb** [comment]
@hifn123p 那你们的小程序不久不能用吗，都登陆不了

**Comment by hifn123p** [comment]
本来就是去年一个课的作业，服务器小程序早就停了，不用了

**Comment by vintingb** [comment]
@hifn123p 那谢谢了

**Comment by hifn123p** [comment]
qq多少，等有空可以交流下

**Comment by vintingb** [comment]
> qq多少，等有空可以交流下

1207838527
